.read /u1/cs348/public/sqlite/createschema.sql
.read /u1/cs348/public/sqlite/populate.sql

/*

*/

CREATE TABLE TRY_HARD AS
SELECT DISTINCT SNO,CNO,MARK,TERM,SECTION
FROM Enrollment
GROUP BY SNO,CNO,TERM,SECTION
      HAVING MARK>98;

CREATE TABLE AVERAGE AS
SELECT DISTINCT TRY_HARD.SNO,TRY_HARD.CNO,TRY_HARD.MARK,AVG(Enrollment.MARK) AS Average_Mark
FROM TRY_HARD INNER JOIN Enrollment on
     TRY_HARD.CNO=Enrollment.CNO AND
     TRY_HARD.TERM=Enrollment.TERM AND
     TRY_HARD.SECTION=Enrollment.SECTION
GROUP BY TRY_HARD.CNO,TRY_HARD.SECTION,TRY_HARD.TERM;

SELECT TRY_HARD.SNO
FROM AVERAGE;
